### ISSUE TITLE
Right side bar

### ISSUE THREAD

**Issue by Jpickard1** [Jpickard1/RAG-DEV#39]
(1) make it look nice
(2) add options to set agent/RAG configurations
    - number of docs
    - type of search
    - etc.
(3) display LLM API usage to user
    - this will come from `/api/invoke` as a new field in the JSON

**Comment by Jpickard1** [comment]
Changes made to logging api calls and invoke endpoint. To display the LLM API usage/cost, the `/invoke` endpoint will return a JSON with the following structure (See [PR44](https://github.com/Jpickard1/BRAD/pull/44)):
```
    >>> { 
    >>>      "response": "Generated response from BRAD agent", 
    >>>      "response-log": { 
    >>>          "stage_1": "log entry for stage 1", 
    >>>          "stage_2": "log entry for stage 2", 
    >>>          ...
    >>>      },
    >>>      "llm-usage": {
    >>>          "llm-calls": number of new llm calls,
    >>>          "api-fees":  cost of api fees,
    >>>      }
    >>> }
```
@imnuvi lmk if this seems useful/you can do the front end part to display this

**Comment by imnuvi** [comment]
@Jpickard1 This looks good. I will update the frontend to display this info.

**Comment by Jpickard1** [comment]
TODO: JP will change API to report both running totals (using current structure) and the amount used for the individual query to `/invoke`
