### ISSUE TITLE
global management of app execution

### ISSUE THREAD

**Issue by Jpickard1** [Jpickard1/RAG-DEV#41]
We should create some scheme for managing the use of global variables in the app. Allowing the `Agent` to be global works for now -- but it seems likely to cause errors in the future.

Low priority until next week, but  @imnuvi  it would be good if you have thoughts on how we can/should do this

**Comment by imnuvi** [comment]
Best way to go about this is to have a factory that generates agents when required and automatically closes them when execution goes out of scope of the function.

**Comment by imnuvi** [comment]
Fixed in [frontend_rem_globals](https://github.com/Jpickard1/BRAD/tree/frontend_rem_globals)

**Comment by Jpickard1** [comment]
That branch looks good! Could you please add some docstrings to explain how to use the `AgentFactory` class @imnuvi and then perhaps it's ready to merge?

**Comment by imnuvi** [comment]
Sure, I'll add docs.
