### ISSUE TITLE
Sidebar styling

### ISSUE THREAD

**Issue by imnuvi** [Jpickard1/RAG-DEV#62]
Make the right sidebar stylist and modern

**Comment by imnuvi** [comment]
<img width="389" alt="Screenshot 2024-11-15 at 2 45 34 PM" src="https://github.com/user-attachments/assets/14ae1292-d288-4e82-9155-90cf2ec71c8b">
<img width="389" alt="Screenshot 2024-11-15 at 2 45 46 PM" src="https://github.com/user-attachments/assets/68a1eaeb-e6f2-4150-aa48-3a42c8084a59">

Updated styles

**Comment by Jpickard1** [comment]
LGTM and merged, thanks dude!
