### ISSUE TITLE
Deploy as web server

### ISSUE THREAD

**Issue by Jpickard1** [Jpickard1/RAG-DEV#67]
We should add documentation on how to deploy the system as a web server

ADD:
- [ ] discuss what new code is necessary to do this
- [ ] set this up on a computer in the lab
- [ ] documentation for setting up the server

**Comment by imnuvi** [comment]
Approach:

- We will  have an actual web server like apache or nginx
- We will compile the frontend and use the same server to provide the frontend to the user.
- We will implement very basic authentication for the user.
