### ISSUE TITLE
Database Search to GUI

### ISSUE THREAD

**Issue by Jpickard1** [Jpickard1/RAG-DEV#72]
**Is your feature request related to a problem? Please describe.**
As a user of the GUI, I'd like access to searching online databases similar to how it works in the command line.

**Describe the solution you'd like**
This should look something like how arxiv search works. It would be good to demonstrate this for at least one of the following databases, which should have python implmenetations:

- [ ] Gene Ontology
- [ ] Enrichr
- [ ] BLAST

**Additional context**
During the planning meeting w/ JP, RP, and IR, we determined not to include this feature in the GUI.
Having implemented arxiv search, it seems reasonable to add this feature

**Comment by Jpickard1** [comment]
- [x] Add search settings (https://github.com/Jpickard1/BRAD/commit/5b7ceb3a5d594a9187d4e06b9de6bf2402b0708d)
- [ ] Display output from search to GUI
- [ ] Enrichr
- [ ] Gene Ontology
- [ ] BLAST

**Comment by Jpickard1** [comment]
@imnuvi How can I display an image in the frontend? the image is generated from a database and I suppose could be sent via the FLASK api, but how should that appear in the messages container given the markdown formatting package you selected?

**Comment by imnuvi** [comment]
@Jpickard1 This depends on how the image is stored and where on the frontend it will be used

If the image is stored somewhere on the filesystem, we can just send it to the frontend as a static file. If it gets streamed from some api, we can also directly send it to the frontend via an api but this will be inefficient compared to static file serving.
With regards to the md rendering package marked, they do support image tags and can be enabled with a flag.
