### ISSUE TITLE
onclick of SEARCH results throws an error

### ISSUE THREAD

**Issue by Jpickard1** [Jpickard1/RAG-DEV#92]
**Describe the bug**
When clicking on the response text from BRAD, the a major error prevents the user from continuing the conversation without refreshing or restarting the system. It is important to fix this one because it entirely disables the system

**To Reproduce**
1. Enter the prompt `/force DATABASE search enrichr for MYOD, MYOG, CMYC, CLOCK, PCNA, and related genes`
2. Click on the text of the BRAD response

**Expected behavior**

**Screenshots**
*Initial Output* (truncated)
![image](https://github.com/user-attachments/assets/4e600c8b-0b87-45bc-aa16-651b99194892)

*Onclick displayed bug*
![image](https://github.com/user-attachments/assets/7cc3bbf8-4f27-488f-98af-4179b932bed7)

*After closing out of the displayed bug*
![image](https://github.com/user-attachments/assets/710bca76-bded-4322-b0b9-978f70c21412)

**Comment by imnuvi** [comment]
Fixed in ram/docker_bugfix
